### ISSUE TITLE
人人美剧api加载不到数据了

### ISSUE THREAD

**Issue by baikingrio** [ximencx/XMVideo#1]
人人美剧api加载不到数据了
api返回客户端版本过低的提示

**Comment by ximencx** [comment]
人人美剧，header需要有客户端版本。你可以重新抓下相关接口

**Comment by laymanZ** [comment]
你好，运行你的demo之后加载不出数据，可以正常运行和导入

**Comment by yanweijia** [comment]
加载不了数据的话可以重新抓一下包的，原来的协议老了

**Comment by ximencx** [comment]
新的提交，，改变了数据源。
